services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_node
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - net1
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - net1
volumes:
  mongo_data:
networks:
  net1:
